name: Python CI
on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yaml'

jobs:
  build-gui:
    name: Build GUI
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Download releases to bundle
      run: |
        mkdir releases
        mkdir releases\0.3.0
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.3.0/framework_ansi_default_v0.3.0.uf2 -OutFile releases\0.3.0\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.3.0/framework_iso_default_v0.3.0.uf2 -OutFile releases\0.3.0\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.3.0/framework_jis_default_v0.3.0.uf2 -OutFile releases\0.3.0\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.3.0/framework_numpad_default_v0.3.0.uf2 -OutFile releases\0.3.0\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.3.0/framework_macropad_default_v0.3.0.uf2 -OutFile releases\0.3.0\framework_macropad_default.uf2
        mkdir releases\0.2.9
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.9/framework_ansi_default_v0.2.9.uf2 -OutFile releases\0.2.9\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.9/framework_iso_default_v0.2.9.uf2 -OutFile releases\0.2.9\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.9/framework_jis_default_v0.2.9.uf2 -OutFile releases\0.2.9\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.9/framework_numpad_default_v0.2.9.uf2 -OutFile releases\0.2.9\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.9/framework_macropad_default_v0.2.9.uf2 -OutFile releases\0.2.9\framework_macropad_default.uf2
        mkdir releases\0.2.8
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.8/framework_ansi_default_v0.2.8.uf2 -OutFile releases\0.2.8\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.8/framework_iso_default_v0.2.8.uf2 -OutFile releases\0.2.8\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.8/framework_jis_default_v0.2.8.uf2 -OutFile releases\0.2.8\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.8/framework_numpad_default_v0.2.8.uf2 -OutFile releases\0.2.8\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.8/framework_macropad_default_v0.2.8.uf2 -OutFile releases\0.2.8\framework_macropad_default.uf2
        mkdir releases\0.2.7
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.7/framework_ansi_default_v0.2.7.uf2 -OutFile releases\0.2.7\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.7/framework_iso_default_v0.2.7.uf2 -OutFile releases\0.2.7\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.7/framework_jis_default_v0.2.7.uf2 -OutFile releases\0.2.7\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.7/framework_numpad_default_v0.2.7.uf2 -OutFile releases\0.2.7\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.7/framework_macropad_default_v0.2.7.uf2 -OutFile releases\0.2.7\framework_macropad_default.uf2
        mkdir releases\0.2.6
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.6/framework_ansi_default_v0.2.6.uf2 -OutFile releases\0.2.6\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.6/framework_iso_default_v0.2.6.uf2 -OutFile releases\0.2.6\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.6/framework_jis_default_v0.2.6.uf2 -OutFile releases\0.2.6\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.6/framework_numpad_default_v0.2.6.uf2 -OutFile releases\0.2.6\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.6/framework_macropad_default_v0.2.6.uf2 -OutFile releases\0.2.6\framework_macropad_default.uf2
        mkdir releases\0.2.5
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.5/framework_ansi_default_v0.2.5.uf2 -OutFile releases\0.2.5\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.5/framework_iso_default_v0.2.5.uf2 -OutFile releases\0.2.5\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.5/framework_jis_default_v0.2.5.uf2 -OutFile releases\0.2.5\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.5/framework_numpad_default_v0.2.5.uf2 -OutFile releases\0.2.5\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.5/framework_macropad_default_v0.2.5.uf2 -OutFile releases\0.2.5\framework_macropad_default.uf2
        mkdir releases\0.2.4
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.4/framework_ansi_default_v0.2.4.uf2 -OutFile releases\0.2.4\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.4/framework_iso_default_v0.2.4.uf2 -OutFile releases\0.2.4\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.4/framework_jis_default_v0.2.4.uf2 -OutFile releases\0.2.4\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.4/framework_numpad_default_v0.2.4.uf2 -OutFile releases\0.2.4\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.4/framework_macropad_default_v0.2.4.uf2 -OutFile releases\0.2.4\framework_macropad_default.uf2
        mkdir releases\0.2.3
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.3/framework_ansi_default_v0.2.3.uf2 -OutFile releases\0.2.3\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.3/framework_iso_default_v0.2.3.uf2 -OutFile releases\0.2.3\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.3/framework_jis_default_v0.2.3.uf2 -OutFile releases\0.2.3\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.3/framework_numpad_default_v0.2.3.uf2 -OutFile releases\0.2.3\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.3/framework_macropad_default_v0.2.3.uf2 -OutFile releases\0.2.3\framework_macropad_default.uf2
        mkdir releases\0.2.2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.2/framework_ansi_default_v0.2.2.uf2 -OutFile releases\0.2.2\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.2/framework_iso_default_v0.2.2.uf2 -OutFile releases\0.2.2\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.2/framework_jis_default_v0.2.2.uf2 -OutFile releases\0.2.2\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.2/framework_numpad_default_v0.2.2.uf2 -OutFile releases\0.2.2\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.2/framework_macropad_default_v0.2.2.uf2 -OutFile releases\0.2.2\framework_macropad_default.uf2
        mkdir releases\0.2.1
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.1/framework_ansi_default_v0.2.1.uf2 -OutFile releases\0.2.1\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.1/framework_iso_default_v0.2.1.uf2 -OutFile releases\0.2.1\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.1/framework_jis_default_v0.2.1.uf2 -OutFile releases\0.2.1\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.1/framework_numpad_default_v0.2.1.uf2 -OutFile releases\0.2.1\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.1/framework_macropad_default_v0.2.1.uf2 -OutFile releases\0.2.1\framework_macropad_default.uf2
        mkdir releases\0.2.0
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.0/framework_ansi_default_v0.2.0.uf2 -OutFile releases\0.2.0\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.0/framework_iso_default_v0.2.0.uf2 -OutFile releases\0.2.0\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.0/framework_jis_default_v0.2.0.uf2 -OutFile releases\0.2.0\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.0/framework_numpad_default_v0.2.0.uf2 -OutFile releases\0.2.0\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.2.0/framework_macropad_default_v0.2.0.uf2 -OutFile releases\0.2.0\framework_macropad_default.uf2
        mkdir releases\0.1.9
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.9/framework_ansi_default_v0.1.9.uf2 -OutFile releases\0.1.9\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.9/framework_iso_default_v0.1.9.uf2 -OutFile releases\0.1.9\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.9/framework_jis_default_v0.1.9.uf2 -OutFile releases\0.1.9\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.9/framework_numpad_default_v0.1.9.uf2 -OutFile releases\0.1.9\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.9/framework_macropad_default_v0.1.9.uf2 -OutFile releases\0.1.9\framework_macropad_default.uf2
        mkdir releases\0.1.8
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.8/framework_ansi_default.uf2 -OutFile releases\0.1.8\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.8/framework_iso_default.uf2 -OutFile releases\0.1.8\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.8/framework_jis_default.uf2 -OutFile releases\0.1.8\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.8/framework_numpad_default.uf2 -OutFile releases\0.1.8\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.8/framework_gridpad_default.uf2 -OutFile releases\0.1.8\framework_gridpad_default.uf2
        mkdir releases\0.1.7
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.7/framework_ansi_default_v0.1.7.uf2 -OutFile releases\0.1.7\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.7/framework_iso_default_v0.1.7.uf2 -OutFile releases\0.1.7\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.7/framework_jis_default_v0.1.7.uf2 -OutFile releases\0.1.7\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.7/framework_numpad_default_v0.1.7.uf2 -OutFile releases\0.1.7\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.7/framework_gridpad_default_v0.1.7.uf2 -OutFile releases\0.1.7\framework_gridpad_default.uf2
        mkdir releases\0.1.6
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.6/framework_ansi_default.uf2 -OutFile releases\0.1.6\framework_ansi_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.6/framework_iso_default.uf2 -OutFile releases\0.1.6\framework_iso_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.6/framework_jis_default.uf2 -OutFile releases\0.1.6\framework_jis_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.6/framework_numpad_default.uf2 -OutFile releases\0.1.6\framework_numpad_default.uf2
        Invoke-WebRequest -Uri https://github.com/FrameworkComputer/qmk_firmware/releases/download/v0.1.6/framework_gridpad_default.uf2 -OutFile releases\0.1.6\framework_gridpad_default.uf2

    # To run locally, need to make sure to include the pywin32 DLL
    # pyinstaller --onefile, --name qmk_gui, --windowed, --add-data "releases;releases" --path C:\users\skype\appdata\local\packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\localcache\local-packages\Python312\site-packages\pywin32_system32  --icon=res\logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res'  -p python/qmk_hid python/qmk_hid/gui.py
    - name: Create Executable
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.12'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'qmk_gui.exe'
        options: --onefile, --name "qmk_gui", --windowed, --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

    # Similar as above but --name changed and --windowed removed
    # pyinstaller --onefile, --name "framework_flash_ansi_v0.2.9.exe", --add-data "releases;releases" --path C:\users\skype\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\Python311\site-packages\pywin32_system32  --icon=res\logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res'  -p python/qmk_hid python/qmk_hid/gui.py
    - name: ANSI Updater
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.11'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'framework_flash_ansi_v0.2.9.zip'
        options: --onefile, --name "framework_flash_ansi_v0.2.9", --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

    - name: ISO Updater
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.11'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'framework_flash_iso_v0.2.9.zip'
        options: --onefile, --name "framework_flash_iso_v0.2.9", --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

    - name: JIS Updater
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.11'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'framework_flash_jis_v0.2.9.zip'
        options: --onefile, --name "framework_flash_jis_v0.2.9", --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

    - name: Numpad Updater
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.11'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'framework_flash_numpad_v0.2.9.zip'
        options: --onefile, --name "framework_flash_numpad_v0.2.9", --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

    - name: Macropad Updater
      uses: JohnAZoidberg/pyinstaller-action@dont-clean
      with:
        python_ver: '3.11'
        spec: python/qmk_hid/gui.py
        requirements: 'python/requirements.txt'
        upload_exe_with_name: 'framework_flash_macropad_v0.2.9.zip'
        options: --onefile, --name "framework_flash_macropad_v0.2.9", --add-data "releases;releases" --icon=res/logo_cropped_transparent_keyboard_48x48.ico --add-data 'res;res' -p python/qmk_hid

  package-python:
    name: Package Python
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cd python
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade build
        python3 -m pip install --upgrade hatch
        python3 -m pip install --upgrade twine
        python3 -m build
